### ISSUE TITLE
chai-as-promised is listed as a dev dependency

### ISSUE THREAD

**Issue by cjus** [flywheelsports/fwsp-jwt-auth#3]
@artemkochnev Does chai-as-promised need to be a core dependency? Or can it just be a dev dependency?

https://github.com/flywheelsports/fwsp-jwt-auth/commit/17ec952a5a3b4f9a970dde3bc1b967d7161952e7

**Comment by artemkochnev** [comment]
@cjus you're right, it should be a dev dependency. I'll open a PR.
